package org.simulatest.insistencelayer.server.client;

import java.net.http.HttpClient;
import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class RemoteConnection implements Connection {

	private final HttpClient httpClient;
	private final String baseUrl;
	private boolean closed;

	public RemoteConnection(HttpClient httpClient, String baseUrl) {
		this.httpClient = httpClient;
		this.baseUrl = baseUrl;
	}

	@Override
	public Statement createStatement() {
		return new RemoteStatement(httpClient, baseUrl);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) {
		return new RemotePreparedStatement(httpClient, baseUrl, sql);
	}

	// ── No-ops (connection lifecycle managed by server) ──

	@Override public void commit() {}
	@Override public void rollback() {}
	@Override public void close() { closed = true; }
	@Override public boolean isClosed() { return closed; }
	@Override public void setAutoCommit(boolean autoCommit) {}
	@Override public boolean getAutoCommit() { return false; }

	// ── Basic getters ──

	@Override public DatabaseMetaData getMetaData() throws SQLException { throw unsupported(); }
	@Override public void setReadOnly(boolean readOnly) {}
	@Override public boolean isReadOnly() { return false; }
	@Override public void setCatalog(String catalog) {}
	@Override public String getCatalog() { return null; }
	@Override public void setTransactionIsolation(int level) {}
	@Override public int getTransactionIsolation() { return TRANSACTION_READ_COMMITTED; }
	@Override public SQLWarning getWarnings() { return null; }
	@Override public void clearWarnings() {}
	@Override public boolean isValid(int timeout) { return !closed; }

	// ── Statement creation variants ──

	@Override public Statement createStatement(int resultSetType, int resultSetConcurrency) { return createStatement(); }
	@Override public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) { return createStatement(); }
	@Override public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) { return prepareStatement(sql); }
	@Override public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) { return prepareStatement(sql); }
	@Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) { return prepareStatement(sql); }
	@Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes) { return prepareStatement(sql); }
	@Override public PreparedStatement prepareStatement(String sql, String[] columnNames) { return prepareStatement(sql); }

	// ── Unsupported ──

	@Override public CallableStatement prepareCall(String sql) throws SQLException { throw unsupported(); }
	@Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException { throw unsupported(); }
	@Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { throw unsupported(); }
	@Override public String nativeSQL(String sql) { return sql; }
	@Override public Map<String, Class<?>> getTypeMap() throws SQLException { throw unsupported(); }
	@Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException { throw unsupported(); }
	@Override public void setHoldability(int holdability) {}
	@Override public int getHoldability() { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }
	@Override public Savepoint setSavepoint() throws SQLException { throw unsupported(); }
	@Override public Savepoint setSavepoint(String name) throws SQLException { throw unsupported(); }
	@Override public void rollback(Savepoint savepoint) throws SQLException { throw unsupported(); }
	@Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { throw unsupported(); }
	@Override public Clob createClob() throws SQLException { throw unsupported(); }
	@Override public Blob createBlob() throws SQLException { throw unsupported(); }
	@Override public NClob createNClob() throws SQLException { throw unsupported(); }
	@Override public SQLXML createSQLXML() throws SQLException { throw unsupported(); }
	@Override public void setClientInfo(String name, String value) {}
	@Override public void setClientInfo(Properties properties) {}
	@Override public String getClientInfo(String name) { return null; }
	@Override public Properties getClientInfo() { return new Properties(); }
	@Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { throw unsupported(); }
	@Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { throw unsupported(); }
	@Override public void setSchema(String schema) {}
	@Override public String getSchema() { return null; }
	@Override public void abort(Executor executor) { closed = true; }
	@Override public void setNetworkTimeout(Executor executor, int milliseconds) {}
	@Override public int getNetworkTimeout() { return 0; }
	@Override public <T> T unwrap(Class<T> iface) throws SQLException { throw unsupported(); }
	@Override public boolean isWrapperFor(Class<?> iface) { return false; }

	private static SQLFeatureNotSupportedException unsupported() {
		return new SQLFeatureNotSupportedException("Not supported by RemoteConnection");
	}
}
